/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
public class Complete_test extends javax.swing.JFrame {

    /**
     * Creates new form Complete_Test
     */
    public int a;
    public String lname;
    public Complete_test(int a,String lname) {
        initComponents();
        this.a=a;
        this.lname=lname;
       
    }
    public Complete_test(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r1_1 = new javax.swing.JRadioButton();
        r1_2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        r1_3 = new javax.swing.JRadioButton();
        r1_4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        r2_1 = new javax.swing.JRadioButton();
        r2_2 = new javax.swing.JRadioButton();
        r2_3 = new javax.swing.JRadioButton();
        r2_4 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        r3_3 = new javax.swing.JRadioButton();
        r3_2 = new javax.swing.JRadioButton();
        r3_4 = new javax.swing.JRadioButton();
        r3_1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Mincho", 1, 36)); // NOI18N
        jLabel1.setText("Complete-Test");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 320, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 390, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Mind Quiz");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("This Quiz is just for you, so don't worry-your results are completely private.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 470, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No-One but you has acces to your result, so be honest and don't hold back. ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 500, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("What is your sleep like at the moment?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 430, 30));

        r1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_1ActionPerformed(evt);
            }
        });
        getContentPane().add(r1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        r1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_2ActionPerformed(evt);
            }
        });
        getContentPane().add(r1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("<html>  I sleep no longer than 7-8 hours a night and I don't nap during the day.<br>  I sleep no longer than 10 hours in a 24-hour period including naps.<br>  I sleep no longer than 12 hours in a 24-hour period including naps.<br>  I sleep longer than 12 hours in a 24-hour period including naps </html>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 580, 100));

        r1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_3ActionPerformed(evt);
            }
        });
        getContentPane().add(r1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        r1_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1_4ActionPerformed(evt);
            }
        });
        getContentPane().add(r1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("<html>How long does it usually take you to fall asleep? <br><br> I never take longer than 30 minutes.<br>I take at least 30 minutes, less than half of the time.<br> I take at least 30 minutes, more than half of the time.<br> I take more than 60 minutes, more than half of the time");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 540, 130));

        r2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_1ActionPerformed(evt);
            }
        });
        getContentPane().add(r2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        r2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_2ActionPerformed(evt);
            }
        });
        getContentPane().add(r2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        r2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_3ActionPerformed(evt);
            }
        });
        getContentPane().add(r2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        r2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2_4ActionPerformed(evt);
            }
        });
        getContentPane().add(r2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("<html>Do you enjoy the company of others as much as usual?<br><br> I enjoy socialising as much as I usually do .<br>I notice that I am less interested in socialising with other people .<br> I find I have interest in being around only a select few people .<br> I have virtually no interest in being around people .</html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 540, 130));

        r3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_3ActionPerformed(evt);
            }
        });
        getContentPane().add(r3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, -1, -1));

        r3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_2ActionPerformed(evt);
            }
        });
        getContentPane().add(r3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        r3_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_4ActionPerformed(evt);
            }
        });
        getContentPane().add(r3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        r3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3_1ActionPerformed(evt);
            }
        });
        getContentPane().add(r3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, 180, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, 160, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\0cFvKO.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1020, 610));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\img1.jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 100));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("<html><center><b>RV College Of Engineering</b></center><center>Autonomous Institution Affliated to VTU,Belagavi</center><center>Bengaluru,560059</center></html>");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 520, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 100));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Developed By: Julioush Kumar Das,Shreya Shakshi,Aditya Sukhwal");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 720, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ButtonGroup bg1=new ButtonGroup();
      r1_1.setSelected(false);
      r1_2.setSelected(false);
      r1_3.setSelected(false);
      r1_4.setSelected(false);
      r2_1.setSelected(false);
      r2_2.setSelected(false);
      r2_3.setSelected(false);
      r2_4.setSelected(false);
      r3_1.setSelected(false);
      r3_2.setSelected(false);
      r3_3.setSelected(false);
      r3_4.setSelected(false);
       
       //Form f=new Form();
       
        int avg=(b1+b2+b3)/3;
        System.out.println(avg);
        String disease = null;
        if(avg>=50 && avg<=70)
            disease="Anxiety";
        else if(avg>=70 && avg<=90)
            disease="Depression";
        else if(avg>90)
            disease="Hypertension";
        else if(avg<50)
            disease="Normal";
        try{
          Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/psycology1?useSSL=false","root","admin123");
            Statement stmt=conn.createStatement();
             PreparedStatement smt=conn.prepareStatement("update form1 set disease=? where u_name=?");  
                smt.setString(1,disease);
                 smt.setString(2,lname);//1 specifies the first parameter in the query  
                  System.out.println(a);
                  int i=smt.executeUpdate();  
                  }catch (SQLException e){
        System.out.println("Error"+ e.getMessage());
                  } catch (ClassNotFoundException ex) {
            Logger.getLogger(Complete_test.class.getName()).log(Level.SEVERE, null, ex);
        }
     Test_result ts=new Test_result(a,lname);
        ts.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_jButton1ActionPerformed
int b1;
    private void r1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_1ActionPerformed
        // TODO add your handling code here:
        r1_2.setSelected(false);
        r1_3.setSelected(false);
        r1_4.setSelected(false);
     
      b1=25;
    }//GEN-LAST:event_r1_1ActionPerformed

    private void r1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_2ActionPerformed
        // TODO add your handling code here:
        r1_1.setSelected(false);
        r1_3.setSelected(false);
        r1_4.setSelected(false);
   
      b1=50;
    }//GEN-LAST:event_r1_2ActionPerformed

    private void r1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_3ActionPerformed
        // TODO add your handling code here:
        r1_2.setSelected(false);
        r1_1.setSelected(false);
        r1_4.setSelected(false);
   
      b1=75;
    }//GEN-LAST:event_r1_3ActionPerformed

    private void r1_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1_4ActionPerformed
        // TODO add your handling code here:
        r1_2.setSelected(false);
        r1_3.setSelected(false);
        r1_1.setSelected(false);
     
      b1=100;
    }//GEN-LAST:event_r1_4ActionPerformed
 int b2;
    private void r2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_1ActionPerformed
        // TODO add your handling code here:
         r2_2.setSelected(false);
        r2_3.setSelected(false);
        r2_4.setSelected(false);
      
      b2=25;
    }//GEN-LAST:event_r2_1ActionPerformed

    private void r2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_2ActionPerformed
        // TODO add your handling code here:
         r2_1.setSelected(false);
        r2_3.setSelected(false);
        r2_4.setSelected(false);
     
      b2=50;
    }//GEN-LAST:event_r2_2ActionPerformed

    private void r2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_3ActionPerformed
        // TODO add your handling code here:
         r2_2.setSelected(false);
        r2_1.setSelected(false);
        r2_4.setSelected(false);
   
      b2=75;
    }//GEN-LAST:event_r2_3ActionPerformed

    private void r2_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2_4ActionPerformed
        // TODO add your handling code here:
         r2_2.setSelected(false);
        r2_3.setSelected(false);
        r2_1.setSelected(false);
     
      b2=100;
    }//GEN-LAST:event_r2_4ActionPerformed
int b3;
    private void r3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_1ActionPerformed
        // TODO add your handling code here:
        r3_2.setSelected(false);
        r3_3.setSelected(false);
        r3_4.setSelected(false);
      
      b3=25;
    }//GEN-LAST:event_r3_1ActionPerformed

    private void r3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_2ActionPerformed
        // TODO add your handling code here:
         r3_1.setSelected(false);
        r3_3.setSelected(false);
        r3_4.setSelected(false);
      
      b3=50;
    }//GEN-LAST:event_r3_2ActionPerformed

    private void r3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_3ActionPerformed
        // TODO add your handling code here:
         r3_2.setSelected(false);
        r3_1.setSelected(false);
        r3_4.setSelected(false);
      
      b3=75;
    }//GEN-LAST:event_r3_3ActionPerformed

    private void r3_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3_4ActionPerformed
        // TODO add your handling code here:
         r3_2.setSelected(false);
        r3_3.setSelected(false);
        r3_1.setSelected(false);
      
      b3=100;
    }//GEN-LAST:event_r3_4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        home h=new home();
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Complete_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Complete_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Complete_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Complete_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Complete_test().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton r1_1;
    private javax.swing.JRadioButton r1_2;
    private javax.swing.JRadioButton r1_3;
    private javax.swing.JRadioButton r1_4;
    private javax.swing.JRadioButton r2_1;
    private javax.swing.JRadioButton r2_2;
    private javax.swing.JRadioButton r2_3;
    private javax.swing.JRadioButton r2_4;
    private javax.swing.JRadioButton r3_1;
    private javax.swing.JRadioButton r3_2;
    private javax.swing.JRadioButton r3_3;
    private javax.swing.JRadioButton r3_4;
    // End of variables declaration//GEN-END:variables
}
