/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package query_panels;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class QP4 extends javax.swing.JPanel {

    /**
     * Creates new form QP1
     */
    public QP4() {
        initComponents();
         ArrayList<ArrayList<String>> list1 = new ArrayList<>();
        list1.clear();
         try{
          Class.forName("com.mysql.jdbc.Driver");
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/psycology1","root","admin123");
            Statement stmt=conn.createStatement();
            ResultSet rs;
           // System.out.println(this.lname);
           String query="select l.username,f.address,f.age,f.disease from login1 l inner join form1 f on f.u_name=l.username group by f.u_name;";
              PreparedStatement smt=conn.prepareStatement(query);  
                //smt.setString(1,lname);//1 specifies the first parameter in the query  
                rs=smt.executeQuery();
               
            while(rs.next()){
                ArrayList<String> arr=new ArrayList<>();
               arr.add(rs.getString(1));
               arr.add(rs.getString(2));
               arr.add(rs.getString(3));
               arr.add(rs.getString(4));
               
               list1.add(arr);
               
            }
           /* L1.setText(uname);
            L2.setText(disease);
            L3.setText(advice);*/
            System.out.println();
            
            DefaultTableModel model = (DefaultTableModel) T1.getModel();
                model.setRowCount(0); 
                Object[] sa = new Object[4];
                for(int i=0;i<list1.size();i++){
               sa[0]=list1.get(i).get(0);
               sa[1]=list1.get(i).get(1);
               sa[2]=list1.get(i).get(2);
               sa[3]=list1.get(i).get(3);
               model.addRow(sa);
           }

    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(QP4.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QP4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Address", "Age", "Disease"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(T1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable T1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
